--- # Manifest file nginx DaemonSet Deployment
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deployment
spec:
  selector:
        # nodeSelector: field that you can specify 
    matchLabels:   # these values must matc the labels
        app: nginxdeployment
  template:
    metadata:
      labels:
        app: nginxdeployment
    spec:
      containers:
       - name: nginxdeployment
         image: nginx:latest
         ports:
          - containerPort: 80
