apiVersion: v1
kind: Service
metadata:
  name: front-end-svc
  namespace: neokloud
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
