--- # Target and Task Playbook
- hosts: demo
  user: vinaym
  become: yes
  connection: ssh
  
  tasks:
    - name: install httpd on AWS EC2 Linux nodes
      action: yum name=httpd state=installed
      notify: restart httpd
        
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
