apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hellow-world-rest-api
  name: hellow-world-rest-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hellow-world-rest-api
  type: LoadBalancer
status:
  loadBalancer: {}
