--- # kubectl manifest file to define HorIzental Pod auto scaling (HTA)
kind: Deployment
apiVersion: apps/v1
metadata:
   name: my-hpa-deploy
spec:
   replicas: 1
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod8
       labels:
         name: deployment
     spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
