--- # kubectl manifest file for httpd apache deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: httpddeployment
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: deployment
   template:
     metadata:
       name: httpdpod
       labels:
         name: deployment
     spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 80
