--- # kubectl manifest file to define batch job
apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    metadata:
      name: testjob
    spec:
      containers:
      - name: counter
        image: centos:7
        command: ["bin/bash", "-c", "echo Vinay M-AWS-Testlab; sleep 5"]
      restartPolicy: Never
