--- # My loops Playbook
- hosts: demo
  user: vinaym
  become: yes
  connection: ssh
  tasks: 
         - name: add a list of users in my AWS EC2 Linux Nodes
           user: name='{{item}}' state=present
           with_items:
                      - user1
                      - user2
                      - user3
                      - user4
