apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  securityContext:
    runAsUser: 1001
  containers:
  - image: ubuntu
    name: web
    resources: {}
    command: ["sleep", "5000"]
    securityContext:
      runAsUser: 1002
      capabilities:
       add: ["SYS_TIME", "NET_ADMIN"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
