--- # Manifest file for Replication Controllers
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 3
  selector:
    matchExpressions:   # these values must matc the labels
      - {key: myname, operator: In, values: [vinaym, vinman01, vinay]}
      - {key: env, operator: NotIn, values: [production]}
  template:
    metadata:
      name: replicasetprod
      labels:
        myname: vinaym
    spec:
      containers:
      - name: c00
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo Hello-vinaym; sleep 5 ; done"]
