apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql:8.0
    name: mysql-container
    env:
     - name: mysql-root-pass 
       valueFrom:
              secretKeyRef: 
                  name: mysql-root-pass
                  key: mysql_secret_password 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
