apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neokloud-server
  namespace: auto-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neokloud-server
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
   scaleDown:
    stabilizationWindowSeconds: 30
