--- # manifest file to create nginx pob with port
kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  labels: 
     appname: nginx
     type: web-server
spec:
  containers:
    - name: nginx-c
      image: nginx:latest
      ports:
       - containerPort: 8080
