--- # testpod manifest file
kind: Pod
apiVersion: v1
metadata:
  name: testpod1
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Vinay M; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always
