apiVersion: v1
kind: Pod
metadata:
 name: random-number-gen-pod
spec:
 containers:
 - image: alpine
   name: alpine
   command: ["/bin/sh","-c"]
   args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
   volumeMounts:
   - mountPath: /home/vinaym/data/opt
     name: data-volume

 volumes:
  - name: data-volume 
    hostPath:
     path: /home/vinaym/data
     type: Directory

